FROM golang:1.23 AS builder

WORKDIR /app

COPY . .

RUN go build -v -o math

CMD ["./math"]

FROM scratch

COPY --from=builder /app/math .

CMD ["./math"]                                                           