# must be unique in a given SonarQube instance
sonar.projectKey=go-math

# --- optional properties ---

# defaults to project key
#sonar.projectName=My project
# defaults to 'not provided'
#sonar.projectVersion=1.0
 
# Path is relative to the sonar-project.properties file. Defaults to .
sonar.sources=.
sonar.exclusions=**/*_test.go

sonar.tests=.
sonar.test.inclusions=.**/*_test.go
#sonar.host.url=http://localhost:9000
#sonar.token=sqp_f3960c1d36675ed0c307a4467ee6f08965d20941
sonar.go.coverage.reportPaths=coverage.out

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-
