sonar.projectKey=typevitor_go-math
sonar.organization=typevitor
sonar.projectName=go-math

# Path to sources
sonar.sources=.
sonar.exclusions=**/*_test.go
sonar.inclusions=**/*.go

# Path to tests
sonar.tests=.
sonar.test.inclusions=.**/*_test.go

# Source encoding
sonar.sourceEncoding=UTF-8
sonar.go.coverage.reportPaths=coverage.out

# Exclusions for copy-paste detection
#sonar.cpd.exclusions=