name: ci-math-go
on: [push]
jobs: 
  check-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - run: go test -v math_test.go math.go
      - run: go run math.go