name: ci-math-go

on: 
  pull_request:
    branches:
      - develop

jobs: 
  check-app:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.18', '1.20', '1.22', '1.23']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - run: go test -v math_test.go math.go
      - run: go run math.go